/**
 * Data Demo Resmi — Sistem Surat Tugas BKI Pontianak
 * 
 * Terdiri dari:
 * - 5 Surat Tugas (3 PDS + 2 SPS)
 * - 3 Kwitansi Honorarium (1 Lunas, 2 Belum Dibayar)
 * - 2 Laporan Survei (1 Disetujui, 1 Terkirim CITO)
 */

export const INITIAL_SURAT_TUGAS = [
  {
    id: 'ST-DEMO-LN-001',
    nomor: 'A 0    /SV.201/PK/KI-25',
    noAgenda: 'AG-LN-001',
    agenda: 'AG-LN-001',
    namaKapal: 'LCT SHUN JUN 7',
    pemohon: 'PEMOHON SURVEY KLAS',
    docType: 'PDS',
    isPds: true,
    isSps: false,
    pdsType: 'luar_negeri',
    isLuarNegeri: true,
    negaraTujuan: 'CHINA',
    perihal: 'DINAS SURVEY KLAS',
    jenisSurvey: 'DINAS SURVEY KLAS',
    petugas: 'TRI LAKSONO JOENIAWAN',
    pangkat: 'GRADE 6 A',
    jabatan: 'SURVEYOR',
    tempatSurvey: 'CHINA',
    lokasi: 'CHINA',
    tglMulai: '2025-11-24',
    tglSelesai: '2025-11-26',
    // Rincian Luar Negeri (USD)
    hariLuarNegeri: 3,
    malamLuarNegeri: 2,
    hariLiburLuarNegeri: 0,
    tiketLuarNegeriUsd: 0,
    asalTujuanLuarUsd: 0,
    uangHarianUsdRate: 150,
    uangHarianUsdTotal: 450,
    uangHotelUsdRate: 0,
    uangHotelUsdTotal: 0,
    hariLiburUsdTotal: 0,
    pakaianDinginUsd: 0,
    totalUsd: 450,
    // Rincian Transit Dalam Negeri (IDR)
    tglMulaiTransit: '2025-11-09',
    tglSelesaiTransit: '2025-11-11',
    tiketDalamNegeri: 0,
    asalTujuanDlm: 750000,
    totalTransitIdr: 750000,
    // Kurs & Konversi
    kursUsd: 16640,
    konversiUsdKeIdr: 7488000,
    jumlahEstimasi: 8238000,
    totalIdrTerima: 8238000,
    keteranganLain: 'TIKET, HOTEL DAN TAT DI LUAR NEGERI DITANGGUNG PEMOHON',
    status: 'Selesai',
    approvalStatus: 'ACC',
    approvalDate: '2025-11-26T10:00:00.000Z',
    approvedBy: 'MUHSON NURROCHMAT',
    kepalaCabang: 'MUHSON NURROCHMAT',
    nup: '48199-KI'
  },
  {
    id: 'ST-DEMO-001',
    nomor: 'A 0    /SV.245/PK/KI-26',
    noAgenda: 'AG-245/PK',
    agenda: 'AG-245/PK',
    namaKapal: 'KM MUTIARA LAUT',
    pemohon: 'PT. PELAYARAN NASIONAL',
    docType: 'PDS',
    isPds: true,
    isSps: false,
    perihal: 'ANNUAL SURVEY & CERTIFICATION',
    jenisSurvey: 'Annual Survey',
    petugas: 'ALFIAN BONE PUTRA',
    pangkat: 'GRADE 6 A',
    jabatan: 'SURVEYOR',
    tempatSurvey: 'Pontianak',
    lokasi: 'Pontianak',
    tglMulai: '2026-09-01',
    tglSelesai: '2026-09-02',
    sarana: 'Darat',
    saranaTransportasi: 'Darat / Mobil Dinas',
    kategoriTransportasi: 'Dalam Kota',
    kategoriPerjalanan: 'Dalam Kota',
    status: 'Selesai',
    approvalStatus: 'ACC',
    approvalDate: '2026-09-02T10:00:00.000Z',
    approvedBy: 'MUHSON NURROCHMAT',
    tarifDasar: 3000000,
    uangHarian: 300000,
    biayaTiket: 0,
    tiketHotel: 0,
    tiketPesawatTaxi: 0,
    jumlahEstimasi: 3000000,
    isCito: false,
    catatan: 'Pemeriksaan tahunan lambung dan permesinan lengkap. Disetujui.',
    kepalaCabang: 'MUHSON NURROCHMAT',
    nup: '48199-KI'
  },
  {
    id: 'ST-DEMO-002',
    nomor: 'A 0    /SV.246/PK/KI-26',
    noAgenda: 'AG-246/PK',
    agenda: 'AG-246/PK',
    namaKapal: 'TB SAMUDERA JAYA',
    pemohon: 'PT. MARITIM SAMUDERA',
    docType: 'PDS',
    isPds: true,
    isSps: false,
    perihal: 'DOCKING SURVEY & BOTTOM INSPECTION',
    jenisSurvey: 'Docking Survey',
    petugas: 'SANDI NANDARIANTO',
    pangkat: 'GRADE 5 C',
    jabatan: 'SURVEYOR',
    tempatSurvey: 'Batam',
    lokasi: 'Batam',
    tglMulai: '2026-09-03',
    tglSelesai: '2026-09-05',
    sarana: 'Pesawat Terbang',
    saranaTransportasi: 'Udara dan Darat',
    kategoriTransportasi: 'Pesawat Terbang',
    kategoriPerjalanan: 'Luar Kota',
    status: 'Selesai',
    approvalStatus: 'ACC',
    approvalDate: '2026-09-05T14:30:00.000Z',
    approvedBy: 'MUHSON NURROCHMAT',
    tarifDasar: 4500000,
    uangHarian: 275000,
    biayaTiket: 3300000,
    tiketHotel: 0,
    tiketPesawatTaxi: 3300000,
    jumlahEstimasi: 7800000,
    isCito: true,
    catatan: 'Docking survey CITO hari libur, pengujian ketebalan pelat dasar laut.',
    kepalaCabang: 'MUHSON NURROCHMAT',
    nup: '48199-KI'
  },
  {
    id: 'ST-DEMO-003',
    nomor: 'A 0    /SV.247/PK/KI-26',
    noAgenda: 'AG-247/PK',
    agenda: 'AG-247/PK',
    namaKapal: 'MV NUSANTARA EXPRESS',
    pemohon: 'PT. NUSANTARA LINES',
    docType: 'PDS',
    isPds: true,
    isSps: false,
    perihal: 'INTERMEDIATE SURVEY & LOAD LINE',
    jenisSurvey: 'Intermediate Survey',
    petugas: 'ANDRE GUNTUR',
    pangkat: 'GRADE 6 A',
    jabatan: 'SURVEYOR',
    tempatSurvey: 'Jakarta',
    lokasi: 'Jakarta',
    tglMulai: '2026-09-04',
    tglSelesai: '2026-09-07',
    sarana: 'Pesawat Terbang',
    saranaTransportasi: 'Udara dan Darat',
    kategoriTransportasi: 'Pesawat Terbang',
    kategoriPerjalanan: 'Luar Kota',
    status: 'Berjalan',
    approvalStatus: 'Menunggu ACC',
    tarifDasar: 3500000,
    uangHarian: 300000,
    biayaTiket: 2400000,
    tiketHotel: 0,
    tiketPesawatTaxi: 2400000,
    jumlahEstimasi: 5900000,
    isCito: false,
    catatan: 'Survei antara sedang berjalan di Pelabuhan Tanjung Priok.',
    kepalaCabang: 'MUHSON NURROCHMAT',
    nup: '48199-KI'
  },
  {
    id: 'ST-DEMO-004',
    nomor: '-',
    noAgenda: 'AG-248/PK',
    agenda: 'AG-248/PK',
    namaKapal: 'KM PELITA MARITIM',
    pemohon: 'PT. PELITA BAHARI',
    docType: 'SPS',
    isPds: false,
    isSps: true,
    perihal: 'PERMOHONAN RENEWAL SURVEY',
    jenisSurvey: 'Renewal Survey',
    petugas: 'SEPTIAN AJI DEWANGKARA',
    pangkat: 'GRADE 5 C',
    jabatan: 'SURVEYOR',
    tempatSurvey: 'Surabaya',
    lokasi: 'Surabaya',
    tglMulai: '2026-09-10',
    tglSelesai: '2026-09-12',
    status: 'Menunggu Survei',
    approvalStatus: 'Menunggu ACC',
    isParafSent: true,
    parafSentAt: '2026-09-03T09:00:00.000Z',
    parafSentBy: 'RENZA MUHARAM',
    tarifDasar: 0,
    jumlahEstimasi: 0,
    catatan: 'SPS terbit, paraf telah dikirimkan ke pemohon via email.'
  },
  {
    id: 'ST-DEMO-005',
    nomor: '-',
    noAgenda: 'AG-249/PK',
    agenda: 'AG-249/PK',
    namaKapal: 'TB KARTIKA 05',
    pemohon: 'PT. KARTIKA LOGISTIK',
    docType: 'SPS',
    isPds: false,
    isSps: true,
    perihal: 'PERMOHONAN ANNUAL SURVEY TONGKANG',
    jenisSurvey: 'Annual Survey',
    petugas: 'ALFIAN BONE PUTRA',
    pangkat: 'GRADE 6 A',
    jabatan: 'SURVEYOR',
    tempatSurvey: 'Pontianak',
    lokasi: 'Pontianak',
    tglMulai: '2026-09-15',
    tglSelesai: '2026-09-16',
    status: 'Menunggu Survei',
    approvalStatus: 'Menunggu ACC',
    isParafSent: false,
    tarifDasar: 0,
    jumlahEstimasi: 0,
    catatan: 'Permohonan baru masuk, menunggu verifikasi dokumen dan pengiriman paraf.'
  }
];

export const INITIAL_KWITANSI_HONOR = [
  {
    id: 'KW-DEMO-001',
    suratId: 'ST-DEMO-001',
    nomorSurat: 'A 0    /SV.245/PK/KI-26',
    namaKapal: 'KM MUTIARA LAUT',
    penerima: 'ALFIAN BONE PUTRA',
    lokasi: 'Pontianak',
    tarifDasar: 3000000,
    biayaTiket: 0,
    tiketHotel: 0,
    tiketPesawatTaxi: 0,
    kategoriTransportasi: 'Darat / Mobil Dinas',
    jumlah: 3000000,
    status: 'Sudah Dibayar',
    tglBayar: '2026-09-03',
    catatan: 'Honorarium Annual Survey KM MUTIARA LAUT telah ditransfer.'
  },
  {
    id: 'KW-DEMO-002',
    suratId: 'ST-DEMO-002',
    nomorSurat: 'A 0    /SV.246/PK/KI-26',
    namaKapal: 'TB SAMUDERA JAYA',
    penerima: 'SANDI NANDARIANTO',
    lokasi: 'Batam',
    tarifDasar: 4500000,
    biayaTiket: 3300000,
    tiketHotel: 0,
    tiketPesawatTaxi: 3300000,
    kategoriTransportasi: 'Pesawat Terbang',
    jumlah: 7800000,
    status: 'Belum Dibayar',
    tglBayar: '',
    catatan: 'Honorarium CITO Batam + Reimbursment tiket pesawat Lion Air.'
  },
  {
    id: 'KW-DEMO-003',
    suratId: 'ST-DEMO-003',
    nomorSurat: 'A 0    /SV.247/PK/KI-26',
    namaKapal: 'MV NUSANTARA EXPRESS',
    penerima: 'ANDRE GUNTUR',
    lokasi: 'Jakarta',
    tarifDasar: 3500000,
    biayaTiket: 2400000,
    tiketHotel: 0,
    tiketPesawatTaxi: 2400000,
    kategoriTransportasi: 'Pesawat Terbang',
    jumlah: 5900000,
    status: 'Belum Dibayar',
    tglBayar: '',
    catatan: 'Honorarium Intermediate Survey Jakarta + tiket pesawat Garuda.'
  }
];

export const INITIAL_LAPORAN_SURVEI = [
  {
    id: 'LAP-DEMO-001',
    suratId: 'ST-DEMO-001',
    namaKapal: 'KM MUTIARA LAUT',
    petugas: 'ALFIAN BONE PUTRA',
    pangkat: 'GRADE 6 A',
    lokasi: 'Pontianak',
    lokasiSurvey: 'Pontianak',
    namaSurvey: 'Annual Survey',
    tglLapor: '2026-09-02',
    tanggal: '2026-09-02',
    isCito: false,
    tarifDasar: 3000000,
    nilai: 3000000,
    hasil: 'Pemeriksaan lambung, pelat geladak, dan permesinan bantu dalam kondisi baik sesuai regulasi BKI. Sertifikat pembaruan diterbitkan.',
    status: 'Disetujui'
  },
  {
    id: 'LAP-DEMO-002',
    suratId: 'ST-DEMO-002',
    namaKapal: 'TB SAMUDERA JAYA',
    petugas: 'SANDI NANDARIANTO',
    pangkat: 'GRADE 5 C',
    lokasi: 'Batam',
    lokasiSurvey: 'Batam',
    namaSurvey: 'Docking Survey',
    tglLapor: '2026-09-05',
    tanggal: '2026-09-05',
    isCito: true,
    tarifDasar: 4500000,
    nilai: 7800000,
    hasil: '[⚡ CITO] Penggantian pelat dasar ganda sekat 12-24 telah selesai dilas dan diuji vakum. Dokumen docking lengkap diserahkan.',
    status: 'Terkirim'
  }
];
